apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}

  