apiVersion: apps/v1
kind: Deployment
metadata:
  name: ide-dirceu
  namespace: aluno-dirceu
spec:
  selector:
     matchLabels:
       app: ide
  strategy:
     type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ide
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: vol-1
        persistentVolumeClaim:
           claimName: pvc-ide
      containers:
      - image: rishikoy/theiaide-full:1.0.0-SNAPSHOT
        name: ide
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /home/project
          name: vol-1

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
  - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}

  